apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-
  namespace: bud
spec:
  pipelineRef:
    name: buildah
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: ws1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
